### ISSUE TITLE
Textual Schema Editor?

### ISSUE THREAD

**Issue by APMU** [findyourmagic/dber#41]
Hi Guys!

Dber is amazing!

Is it possible add a textual/dbml schema editor, like dbdiagram.io?

Thanks.

Alex
from Brazil

**Comment by alexworldbr** [comment]
@findyourmagic

**Comment by alexworldbr** [comment]
?

**Comment by findyourmagic** [comment]
Hi Alex,

Thank you for your support for DBER! Regarding your suggestion about a dbml schema editor, dbml and dbdiagram.io are indeed projects from the same team, and DBER benefits from the advantages brought by dbml. Therefore, we aim to avoid being too similar to dbdiagram.io. Due to limited resources, there may not be many updates in the near future.
